[Theme]
Name=ShadowOS
Description=Cyberpunk login theme for ShadowOS
Author=Believe Brat
License=Proprietary

[General]
Background=/usr/share/backgrounds/shadowos/wallpaper1.png
Font=JetBrains Mono
AntiAliasing=true

[Users]
ShowUsers=root
ShowUserBackground=/usr/share/backgrounds/shadowos/wallpaper1.png
UserImage=user.png
UserImageSize=96
UserImageBorder=2
UserImageBorderColor=00ffff

[Input]
ShowPassword=false
PasswordMask=●

[Buttons]
ExitButton=false 


